# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5783d13dc4cf0aad0ce08321e3639bed"
name = "codify"
application_url = "https://codify-app-live.vercel.app"
embedded = true
handle = "codify-cod-automation"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions,write_orders,write_draft_orders,write_customers,read_orders,read_draft_orders,read_customers"

[auth]
redirect_urls = [ "https://codify-app-live.vercel.app/api/auth/callback" ]

[app_proxy]
url = "https://codify-app-live.vercel.app/apps/codify-checkout"
subpath = "codify-checkout"
prefix = "apps"

[pos]
embedded = false
