# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5783d13dc4cf0aad0ce08321e3639bed"
application_url = "https://example.com"
embedded = true
name = "codify"
handle = "codify-cod-automation"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_draft_orders,read_orders,write_customers,write_draft_orders,write_metaobject_definitions,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[app_proxy]
url = "https://example.com/apps/codify-checkout"
subpath = "codify-checkout"
prefix = "apps"

[pos]
embedded = false

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]
