import { 
  Order, 
  StaffMember, 
  FormCustomization, 
  WhatsAppConfig, 
  LocationRule, 
  BlacklistItem, 
  AutoTagRule, 
  UpsellOffer, 
  DepositGatewayConfig, 
  AppSettings 
} from '../types';

export const INITIAL_SETTINGS: AppSettings = {
  appActive: true,
  storeName: 'Royal Attire PK - Official COD Store',
  currency: 'PKR',
  currencySymbol: 'Rs.',
  themeAppExtensionActive: true,
  defaultLanguage: 'en',
  enableRtl: false,
  autoAssignStaff: true,
  routingMode: 'QUOTA',
  riskScoreThresholdHigh: 70,
  riskScoreThresholdMedium: 40,
  autoCancelHighRisk: false,
  requireDepositForHighRisk: true,
  planTier: 'PREMIUM',
  billingInterval: 'MONTHLY',
  planMonthlyQuota: 500,
};

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'Hamza Tariq',
    phone: '+92 300 1234567',
    email: 'hamza.t@makcod-store.com',
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    assignedQuota: 100,
    currentAssignedCount: 42,
    confirmedCount: 38,
    cancelledCount: 3,
    rtoCount: 1,
    confirmationRate: 90.5,
    assignedCities: ['Lahore', 'Islamabad', 'Rawalpindi'],
    workingHours: '09:00 AM - 06:00 PM',
  },
  {
    id: 'staff-2',
    name: 'Ayesha Khan',
    phone: '+92 321 9876543',
    email: 'ayesha.k@makcod-store.com',
    role: 'Agent',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    assignedQuota: 150,
    currentAssignedCount: 89,
    confirmedCount: 81,
    cancelledCount: 5,
    rtoCount: 3,
    confirmationRate: 91.0,
    assignedCities: ['Karachi', 'Hyderabad', 'Sukkur'],
    workingHours: '10:00 AM - 07:00 PM',
  },
  {
    id: 'staff-3',
    name: 'Bilal Ahmed',
    phone: '+92 333 5551234',
    email: 'bilal.a@makcod-store.com',
    role: 'Agent',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'ACTIVE',
    assignedQuota: 80,
    currentAssignedCount: 65,
    confirmedCount: 54,
    cancelledCount: 7,
    rtoCount: 4,
    confirmationRate: 83.1,
    assignedCities: ['Faisalabad', 'Multan', 'Peshawar', 'Gujranwala'],
    workingHours: '01:00 PM - 10:00 PM',
  },
  {
    id: 'staff-4',
    name: 'Zainab Noor',
    phone: '+92 345 8899001',
    email: 'zainab.n@makcod-store.com',
    role: 'Agent',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'ON_BREAK',
    assignedQuota: 100,
    currentAssignedCount: 30,
    confirmedCount: 26,
    cancelledCount: 2,
    rtoCount: 2,
    confirmationRate: 86.7,
    assignedCities: ['Sialkot', 'Quetta', 'Abbottabad'],
    workingHours: '09:00 AM - 06:00 PM',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'MC-9821',
    shopifyOrderId: '#10492',
    customerName: 'Muhammad Usman',
    phone: '0300-8451920',
    email: 'usman.m@gmail.com',
    city: 'Lahore',
    province: 'Punjab',
    address: 'House 42-B, Sector C, Bahria Town, Lahore',
    postalCode: '53720',
    items: [
      {
        id: 'it-1',
        title: 'Premium Egyptian Cotton Kurta - Navy Blue',
        variant: 'Size L',
        price: 3499,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=120&auto=format&fit=crop&q=80',
      },
      {
        id: 'it-2',
        title: 'Matching Straight Trouser',
        variant: 'Size L',
        price: 1499,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=120&auto=format&fit=crop&q=80',
      }
    ],
    subtotal: 4998,
    shippingFee: 150,
    codFee: 99,
    discount: 500,
    total: 4747,
    status: 'VERIFIED',
    riskLevel: 'LOW',
    riskScore: 12,
    riskFactors: ['Valid Pakistani Phone Carrier (Jazz)', 'Deliverable Residential Address', 'Verified via 1-Click WhatsApp OTP'],
    assignedStaffId: 'staff-1',
    assignedStaffName: 'Hamza Tariq',
    tags: ['LHR-EXPRESS', 'VERIFIED_WHATSAPP', 'PREMIUM_BUYER'],
    depositRequired: false,
    depositAmount: 0,
    depositStatus: 'NONE',
    whatsappStatus: 'CONFIRMED',
    whatsappSentAt: '10 mins ago',
    createdAt: '2026-08-21T15:40:00Z',
    ipAddress: '111.119.187.23',
    source: 'MakCod Quick Form',
    trackingNumber: 'TRX-99281726',
    courier: 'Trax',
  },
  {
    id: 'MC-9820',
    shopifyOrderId: '#10491',
    customerName: 'Kashif Ali Raza',
    phone: '0312-3344556',
    email: 'kashif.raza22@yahoo.com',
    city: 'Karachi',
    province: 'Sindh',
    address: 'Flat 402, Al-Razi Heights, Gulshan-e-Iqbal Block 13-D',
    postalCode: '75300',
    items: [
      {
        id: 'it-3',
        title: 'Leather Oxford Formal Shoes - Dark Brown',
        variant: 'EU 43',
        price: 6899,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=120&auto=format&fit=crop&q=80',
      }
    ],
    subtotal: 6899,
    shippingFee: 0,
    codFee: 150,
    discount: 0,
    total: 7049,
    status: 'PENDING',
    riskLevel: 'MEDIUM',
    riskScore: 48,
    riskFactors: ['First-time buyer on COD', 'Address contains apartment without landline', 'Order placed after 11 PM'],
    assignedStaffId: 'staff-2',
    assignedStaffName: 'Ayesha Khan',
    tags: ['KHI-COD', 'MEDIUM_RISK', 'WHATSAPP_PENDING'],
    depositRequired: true,
    depositAmount: 500,
    depositStatus: 'PENDING',
    depositMethod: 'EasyPaisa',
    whatsappStatus: 'SENT',
    whatsappSentAt: '25 mins ago',
    createdAt: '2026-08-21T15:20:00Z',
    ipAddress: '39.40.12.88',
    source: 'MakCod Quick Form',
    courier: 'Leopards',
  },
  {
    id: 'MC-9819',
    shopifyOrderId: '#10490',
    customerName: 'Asad Sheikh (Multiple Orders)',
    phone: '0345-0000111',
    email: 'testbuyer99@gmail.com',
    city: 'Peshawar',
    province: 'KPK',
    address: 'Near Chowk Yadgar, Shop 12 (Vague Address)',
    postalCode: '25000',
    items: [
      {
        id: 'it-4',
        title: 'Chronograph Luxury Smartwatch Series 9',
        variant: 'Space Black / Steel',
        price: 8499,
        quantity: 3,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=120&auto=format&fit=crop&q=80',
      }
    ],
    subtotal: 25497,
    shippingFee: 250,
    codFee: 300,
    discount: 0,
    total: 26047,
    status: 'PENDING',
    riskLevel: 'HIGH',
    riskScore: 88,
    riskFactors: [
      'Duplicate phone prefix pattern detected',
      'Extremely high COD cart value (> Rs. 25,000)',
      'Vague address without street or house number',
      '3 orders placed from same IP within 15 minutes'
    ],
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Bilal Ahmed',
    tags: ['FRAUD_SUSPECT', 'HIGH_VALUE_COD', 'REQUIRE_ADVANCE_DEPOSIT', 'RTO_RISK'],
    depositRequired: true,
    depositAmount: 2500,
    depositStatus: 'PENDING',
    depositMethod: 'JazzCash',
    whatsappStatus: 'UNSENT',
    createdAt: '2026-08-21T14:50:00Z',
    ipAddress: '182.185.10.4',
    source: 'Shopify Standard Checkout',
    courier: 'TCS',
  },
  {
    id: 'MC-9818',
    shopifyOrderId: '#10489',
    customerName: 'Fatima Batool',
    phone: '0333-4192837',
    email: 'fatima.batool@outlook.com',
    city: 'Islamabad',
    province: 'Federal',
    address: 'Street 14, House 29, Sector F-8/3, Islamabad',
    postalCode: '44000',
    items: [
      {
        id: 'it-5',
        title: 'Silk Embroidered 3-Piece Stitched Suit',
        variant: 'Medium / Emerald Green',
        price: 7999,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=120&auto=format&fit=crop&q=80',
      }
    ],
    subtotal: 7999,
    shippingFee: 0,
    codFee: 0,
    discount: 800,
    total: 7199,
    status: 'DISPATCHED',
    riskLevel: 'LOW',
    riskScore: 8,
    riskFactors: ['Repeat customer (3 successful deliveries)', 'VIP Postal Code (F-8 Islamabad)', 'WhatsApp verified in 45 seconds'],
    assignedStaffId: 'staff-1',
    assignedStaffName: 'Hamza Tariq',
    tags: ['ISB-VIP', 'REPEAT_BUYER', 'DISPATCHED_TRAX'],
    depositRequired: false,
    depositAmount: 0,
    depositStatus: 'NONE',
    whatsappStatus: 'CONFIRMED',
    whatsappSentAt: '2 hours ago',
    createdAt: '2026-08-21T13:10:00Z',
    ipAddress: '110.38.20.14',
    source: 'Exit-Intent Popup',
    trackingNumber: 'TRX-88192031',
    courier: 'Trax',
  },
  {
    id: 'MC-9817',
    shopifyOrderId: '#10488',
    customerName: 'Rizwan Qureshi',
    phone: '0322-7711223',
    email: 'rizwan.q@gmail.com',
    city: 'Rawalpindi',
    province: 'Punjab',
    address: 'House 88, Road 4, Chaklala Scheme 3, Rawalpindi',
    postalCode: '46000',
    items: [
      {
        id: 'it-6',
        title: 'Wireless Active Noise Cancelling Earbuds Pro',
        variant: 'Matte Black',
        price: 3899,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=120&auto=format&fit=crop&q=80',
      },
      {
        id: 'it-7',
        title: '1-Year Extended Damage Protection Warranty',
        variant: 'Addon',
        price: 399,
        quantity: 1,
        image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=120&auto=format&fit=crop&q=80',
      }
    ],
    subtotal: 4298,
    shippingFee: 150,
    codFee: 99,
    discount: 0,
    total: 4547,
    status: 'DELIVERED',
    riskLevel: 'LOW',
    riskScore: 15,
    riskFactors: ['Successful doorstep delivery completed', 'Payment collected in full'],
    assignedStaffId: 'staff-1',
    assignedStaffName: 'Hamza Tariq',
    tags: ['RWP-DELIVERED', 'WARRANTY_SOLD', 'REVENUE_COLLECTED'],
    depositRequired: false,
    depositAmount: 0,
    depositStatus: 'NONE',
    whatsappStatus: 'CONFIRMED',
    whatsappSentAt: 'Yesterday',
    createdAt: '2026-08-20T10:15:00Z',
    ipAddress: '119.160.67.12',
    source: 'MakCod Quick Form',
    trackingNumber: 'POSTEX-340192',
    courier: 'PostEx',
  },
  {
    id: 'MC-9816',
    shopifyOrderId: '#10487',
    customerName: 'Noman Sadiq (RTO History)',
    phone: '0301-4455667',
    email: 'nomi_badboy@hotmail.com',
    city: 'Faisalabad',
    province: 'Punjab',
    address: 'Near Clock Tower, Bazar 4, Gali 2',
    postalCode: '38000',
    items: [
      {
        id: 'it-8',
        title: 'Heavyweight Fleece Hoodie - Charcoal Grey',
        variant: 'XL',
        price: 2999,
        quantity: 2,
        image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=120&auto=format&fit=crop&q=80',
      }
    ],
    subtotal: 5998,
    shippingFee: 200,
    codFee: 150,
    discount: 0,
    total: 6348,
    status: 'CANCELLED',
    riskLevel: 'CRITICAL',
    riskScore: 94,
    riskFactors: [
      'Phone blacklisted in Pakistani Courier Courier Return Database (2 previous RTOs)',
      'Customer refused to pay Rs. 500 advance security deposit',
      'Auto-cancelled by MakCod AI Rule engine'
    ],
    assignedStaffId: 'staff-3',
    assignedStaffName: 'Bilal Ahmed',
    tags: ['BLACKLISTED_PHONE', 'AUTO_CANCELLED', 'RTO_PREVENTED', 'SAVED_RS_500_COURIER_FEE'],
    depositRequired: true,
    depositAmount: 500,
    depositStatus: 'WAIVED',
    whatsappStatus: 'CANCELLED',
    whatsappSentAt: 'Yesterday',
    createdAt: '2026-08-20T09:00:00Z',
    ipAddress: '175.107.199.5',
    source: 'MakCod Quick Form',
  }
];

export const INITIAL_FORM_CONFIG: FormCustomization = {
  popupTitle: 'Cash on Delivery Quick Checkout',
  popupSubtitle: 'Fill this 15-second form. No card needed. Pay at your doorstep!',
  buttonText: 'Complete Order (Cash on Delivery) 🚚',
  buttonColor: '#008060',
  buttonTextColor: '#ffffff',
  buttonHoverColor: '#006e52',
  headerBgColor: '#047857',
  headerTextColor: '#ffffff',
  formBgColor: '#ffffff',
  textColor: '#202223',
  inputBgColor: '#f8fafc',
  inputBorderColor: '#cbd5e1',
  accentColor: '#10b981',
  fontFamily: 'Inter',
  fontSize: 'md',
  borderRadius: 12,
  cardShadow: 'elevated',
  trustBadgeText: '🔒 100% Doorstep Inspection & 7-Day Easy Exchange Guaranteed',
  showTimer: true,
  timerMinutes: 14,
  timerText: '🔥 High demand! Items in your cart reserved for:',
  showQuantitySelector: true,
  showVariantSelector: true,
  showAddressNotes: true,
  enableOneClickBuy: true,
  enableCityDropdown: true,
  enableFuzzyCityAutocomplete: true,
  fields: [
    { id: 'f-1', name: 'fullName', label: 'Full Name', labelUrdu: 'مکمل نام', labelArabic: 'الاسم الكامل', placeholder: 'e.g. Muhammad Ali', required: true, enabled: true, type: 'text', helpText: 'Enter your legal name for courier verification' },
    { id: 'f-2', name: 'phoneNumber', label: 'WhatsApp / Mobile Number', labelUrdu: 'موبائل نمبر (واٹس ایپ والا)', labelArabic: 'رقم الواتساب', placeholder: '0300-1234567', required: true, enabled: true, type: 'tel', helpText: 'Courier will send delivery updates & OTP via WhatsApp' },
    { id: 'f-3', name: 'city', label: 'Delivery City', labelUrdu: 'شہر', labelArabic: 'المدينة', placeholder: 'Select or type your city', required: true, enabled: true, type: 'select', options: ['Lahore', 'Karachi', 'Islamabad', 'Rawalpindi', 'Faisalabad', 'Multan', 'Peshawar', 'Sialkot', 'Gujranwala', 'Quetta', 'Hyderabad', 'Dubai', 'Riyadh', 'Jeddah'] },
    { id: 'f-4', name: 'address', label: 'Complete Delivery Address', labelUrdu: 'مکمل گھر کا پتہ (گلی، مکان نمبر)', labelArabic: 'العنوان بالتفصيل', placeholder: 'e.g. House # 14, Street 2, Block B, DHA', required: true, enabled: true, type: 'textarea' },
    { id: 'f-5', name: 'nearbyLandmark', label: 'Nearby Landmark (Optional)', labelUrdu: 'قریبی مشہور جگہ یا ہدایات', labelArabic: 'أقرب معلم بارز', placeholder: 'e.g. Near PSO Pump, Deliver before 5 PM', required: false, enabled: true, type: 'text' },
  ],
  exitIntent: {
    enabled: true,
    discountType: 'percentage',
    discountValue: 10,
    headline: 'Wait! Don\'t Miss Out On This Exclusive Deal! 🎁',
    subheadline: 'Get an instant EXTRA 10% OFF + FREE Express Delivery if you complete your order now!',
    timerSeconds: 180,
    couponCode: 'EXIT10_SAVINGS',
    showGiftBadge: true,
    triggerDelayMs: 500,
  }
};

export const INITIAL_WHATSAPP_CONFIG: WhatsAppConfig = {
  mode: 'DIRECT_LINK',
  directLinkPhoneNumber: '+923001234567',
  directLinkCustomMessage: `Assalam-o-Alaikum *{{customer_name}}*! 🛍️\n\nThank you for ordering at *Royal Attire*.\n\n📦 *Order ID:* {{order_id}}\n💰 *Total Amount:* Rs. {{order_total}} (Cash on Delivery)\n📍 *Delivery Address:* {{address}}, {{city}}\n\nPlease reply with *1* to *CONFIRM* this order or *2* to *CANCEL* so we can dispatch your parcel right away!\n\n_Fast tracking: {{confirmation_link}}_`,
  metaPhoneNumberId: '109283749281726',
  metaWabaId: '881920391827364',
  metaAccessToken: 'EAAQ...makcod_secure_token',
  metaWebhookSecret: 'makcod_webhook_secret_99812',
  metaTemplateName: 'makcod_order_verify_v2',
  metaLanguageCode: 'en_US',
  autoSendOnNewOrder: true,
  autoTagConfirmedOrders: true,
  autoCancelTimeoutHours: 24,
  enableQuickReplies: true,
  confirmationKeyword: '1',
  cancellationKeyword: '2',
};

export const INITIAL_LOCATION_RULES: LocationRule[] = [
  {
    id: 'loc-1',
    cityName: 'Lahore',
    postalCodePrefix: '54',
    codEnabled: true,
    codFee: 99,
    freeCodThreshold: 3000,
    estimatedDeliveryDays: '24-48 Hours (Same-Day Option)',
    courierPreference: 'Trax',
    requiresAdvanceDeposit: false,
    depositAmount: 0,
  },
  {
    id: 'loc-2',
    cityName: 'Karachi',
    postalCodePrefix: '75',
    codEnabled: true,
    codFee: 150,
    freeCodThreshold: 4000,
    estimatedDeliveryDays: '2-3 Business Days',
    courierPreference: 'Leopards',
    requiresAdvanceDeposit: false,
    depositAmount: 0,
  },
  {
    id: 'loc-3',
    cityName: 'Islamabad & Rawalpindi',
    postalCodePrefix: '44',
    codEnabled: true,
    codFee: 120,
    freeCodThreshold: 3500,
    estimatedDeliveryDays: '1-2 Business Days',
    courierPreference: 'PostEx',
    requiresAdvanceDeposit: false,
    depositAmount: 0,
  },
  {
    id: 'loc-4',
    cityName: 'Peshawar (High RTO Zone)',
    postalCodePrefix: '25',
    codEnabled: true,
    codFee: 250,
    freeCodThreshold: 6000,
    estimatedDeliveryDays: '3-4 Business Days',
    courierPreference: 'TCS',
    requiresAdvanceDeposit: true,
    depositAmount: 500,
  },
  {
    id: 'loc-5',
    cityName: 'Quetta & Remote Balochistan',
    postalCodePrefix: '87',
    codEnabled: false, // Blocked COD, Prepaid only
    codFee: 350,
    freeCodThreshold: 10000,
    estimatedDeliveryDays: '5-7 Business Days',
    courierPreference: 'M&P',
    requiresAdvanceDeposit: true,
    depositAmount: 1000,
  }
];

export const INITIAL_BLACKLIST: BlacklistItem[] = [
  {
    id: 'bl-1',
    type: 'PHONE',
    value: '03014455667',
    reason: 'Rejected parcel at doorstep 3 times with TCS courier (Fake buyer)',
    addedAt: '2026-08-15',
    blockedAttempts: 4,
    severity: 'BLOCK_ORDER',
  },
  {
    id: 'bl-2',
    type: 'IP',
    value: '182.185.10.4',
    reason: 'Spam order bot placing 10 fake orders every 5 minutes',
    addedAt: '2026-08-19',
    blockedAttempts: 18,
    severity: 'BLOCK_ORDER',
  },
  {
    id: 'bl-3',
    type: 'PHONE',
    value: '03339988112',
    reason: 'Automated bot testing fake addresses and cancelled upon courier arrival',
    addedAt: '2026-08-10',
    blockedAttempts: 2,
    severity: 'REQUIRE_DEPOSIT',
  },
  {
    id: 'bl-4',
    type: 'ADDRESS',
    value: 'Near Chowk Yadgar, Peshawar',
    reason: 'Repeated non-delivery zone where courier cannot find recipients',
    addedAt: '2026-08-01',
    blockedAttempts: 7,
    severity: 'REQUIRE_DEPOSIT',
  }
];

export const INITIAL_UPSELLS: UpsellOffer[] = [
  {
    id: 'up-1',
    title: 'Buy 1 More Get 25% OFF (BOGO Special)',
    subtitle: 'Add a 2nd piece in any size/color for your brother or friend!',
    price: 2499,
    originalPrice: 3499,
    badge: 'MOST POPULAR 🔥',
    type: 'BOGO',
    selectedByDefault: false,
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=150&auto=format&fit=crop&q=80',
    enabled: true,
  },
  {
    id: 'up-2',
    title: 'VIP Express Priority Shipping + Parcel Insurance',
    subtitle: 'Get dispatched in priority batch with 100% loss/damage cover',
    price: 199,
    originalPrice: 400,
    badge: 'FASTEST ⚡',
    type: 'PRIORITY_SHIPPING',
    selectedByDefault: true,
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    enabled: true,
  },
  {
    id: 'up-3',
    title: '1-Year Hassle-Free Exchange & Fabric Warranty',
    subtitle: 'No questions asked doorstep swap if fabric fades or shrinks',
    price: 349,
    originalPrice: 600,
    badge: 'PROTECTION 🛡️',
    type: 'WARRANTY',
    selectedByDefault: false,
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=150&auto=format&fit=crop&q=80',
    enabled: true,
  }
];

export const INITIAL_TAG_RULES: AutoTagRule[] = [
  { id: 'tr-1', name: 'Lahore Express Dispatch', condition: 'City equals Lahore', targetTag: 'LHR-EXPRESS', color: 'green', enabled: true },
  { id: 'tr-2', name: 'Karachi Metro Orders', condition: 'City equals Karachi', targetTag: 'KHI-METRO', color: 'blue', enabled: true },
  { id: 'tr-3', name: 'High Risk / Advance Deposit Required', condition: 'Risk Score >= 70', targetTag: 'RISK_HIGH_DEPOSIT', color: 'red', enabled: true },
  { id: 'tr-4', name: 'WhatsApp 1-Click Confirmed', condition: 'WhatsApp Status equals Confirmed', targetTag: 'VERIFIED_WHATSAPP', color: 'teal', enabled: true },
  { id: 'tr-5', name: 'High Cart Value COD', condition: 'Order Total >= 10000', targetTag: 'VIP_HIGH_VAL', color: 'purple', enabled: true },
  { id: 'tr-6', name: 'Exit Intent Discount Applied', condition: 'Source equals Exit-Intent Popup', targetTag: 'EXIT_DISCOUNT_10', color: 'amber', enabled: true }
];

export const INITIAL_DEPOSIT_GATEWAYS: DepositGatewayConfig = {
  jazzCashEnabled: true,
  jazzCashAccountTitle: 'MakCod Official Store (Pvt Ltd)',
  jazzCashAccountNumber: '0300-8451920',
  easyPaisaEnabled: true,
  easyPaisaAccountTitle: 'Muhammad Usman Khan',
  easyPaisaAccountNumber: '0321-9876543',
  bankTransferEnabled: true,
  bankName: 'Meezan Bank Limited',
  bankAccountTitle: 'MakCod E-Commerce Solutions',
  bankIban: 'PK82MEZN0001092837482910',
  stripeEnabled: false,
  defaultDepositAmount: 500,
  depositMode: 'FIXED',
  depositPercentage: 15,
  minOrderValueForDeposit: 5000,
  autoExemptVerifiedCustomers: true,
  instructionsNote: 'Please send Rs. 500 advance security deposit and WhatsApp the screenshot. The remaining amount will be collected in Cash on Delivery at your doorstep.',
};
