// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/delivery-success": {
    params: {};
  };
  "/app/location-rules": {
    params: {};
  };
  "/app/risk-blacklist": {
    params: {};
  };
  "/app/form-builder": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/analytics": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/whatsapp": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
  "/app/upsells": {
    params: {};
  };
  "/app/team": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/login" | "/auth/*" | "/app" | "/app/delivery-success" | "/app/location-rules" | "/app/risk-blacklist" | "/app/form-builder" | "/app/additional" | "/app/analytics" | "/app/settings" | "/app/whatsapp" | "/app/billing" | "/app/upsells" | "/app/team";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/delivery-success" | "/app/location-rules" | "/app/risk-blacklist" | "/app/form-builder" | "/app/additional" | "/app/analytics" | "/app/settings" | "/app/whatsapp" | "/app/billing" | "/app/upsells" | "/app/team";
  };
  "routes/app.delivery-success.jsx": {
    id: "routes/app.delivery-success";
    page: "/app/delivery-success";
  };
  "routes/app.location-rules.jsx": {
    id: "routes/app.location-rules";
    page: "/app/location-rules";
  };
  "routes/app.risk-blacklist.jsx": {
    id: "routes/app.risk-blacklist";
    page: "/app/risk-blacklist";
  };
  "routes/app.form-builder.jsx": {
    id: "routes/app.form-builder";
    page: "/app/form-builder";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.analytics.jsx": {
    id: "routes/app.analytics";
    page: "/app/analytics";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.whatsapp.jsx": {
    id: "routes/app.whatsapp";
    page: "/app/whatsapp";
  };
  "routes/app.billing.jsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app.upsells.jsx": {
    id: "routes/app.upsells";
    page: "/app/upsells";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.team.jsx": {
    id: "routes/app.team";
    page: "/app/team";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.delivery-success": typeof import("./app/routes/app.delivery-success.jsx");
  "routes/app.location-rules": typeof import("./app/routes/app.location-rules.jsx");
  "routes/app.risk-blacklist": typeof import("./app/routes/app.risk-blacklist.jsx");
  "routes/app.form-builder": typeof import("./app/routes/app.form-builder.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.analytics": typeof import("./app/routes/app.analytics.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.whatsapp": typeof import("./app/routes/app.whatsapp.jsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.jsx");
  "routes/app.upsells": typeof import("./app/routes/app.upsells.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.team": typeof import("./app/routes/app.team.jsx");
};